[server]
port = 8501
address = "0.0.0.0"
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = true
enableWebsocketCompression = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
primaryColor = "#2ecc71"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "auto" 